### ISSUE TITLE
How to obtain the pre-computed CLIP feature of an image?

### ISSUE THREAD

**Issue by JeremyLinky** [liangcici/Probes-VLN#2]
Hi there, I am wondering that if I want to get the room type and the type of objects contained in another image by CLIP, how can I obtain the pre-computed CLIP feature first? Thanks!

**Comment by liangcici** [comment]
Hi, you can use this script to generate the feature: [https://github.com/clip-vil/CLIP-ViL/blob/master/CLIP-ViL-VLN/precomute_imagenet_views.py](url). Set the arch as vit.

**Comment by JeremyLinky** [comment]
That's helpful! Thanks!
